language: node_js
branches:
  only:
  - node-ts
phases:
  install:
    commands:
      - echo Installing source NPM dependencies...
      - npm install -g typescript
      - npm install
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling typescript code to javascript
      - npm run-script build
  post_build:
    commands:
      - echo Build completed on `date`
  deploy:
    provider: heroku
    api_key:
      secure: AVgvTvF1x6yj5ZjHEMcvvJ9c9DgsME9ERp6hI/CrYm82n15HbnlO3OPuGx8KkRqkHKF3K3XdhNBSxck1mPFmIecqHpefx0LWLCOLignB2UOOASnLXYpCvqnu0m+x/l9fFrSIMJm2WYUGWF+8yb8lDxnYqQW+PWZF1bk3tjZ0jcoM8Wl3oLAO0LtYi99oSrL/xWmVcsjzeNwqFVAlxz35Aoxj85825Fvs2R+FeO0steqA+MX04HG9iMxYY2oZemE4MQ9ufS/iBhFrKP1W0mSwSs6BQNswWVtEzB/E/l+TamFPLN5rgwxcHlRUlmJTeVEvWgjNJkM9cuAIjXkLptPP+Ca11Fgos3iGqSWUGZG8FqXmhrTS7G9dZ8eZOrHAijhzYC/eX++4JwvuoezQ42xxsjXnqmB50jRNsj1P12jAczBHyyAx3clIqFbH6Kukd8eFx0yCsx5csqe5nutS6NGWLRWieQqkLZ4ocfS+/PRC7oQiIvylQodM265pzOsMYs36xGDW4+5W3A8w10G59hSQyAbZxBMfHzNfQ31ABn5c3IAroEYywvOznb7Gequ+Y8AqckqoWuto9f0dQkDcRagqepAB7BHutqOQ3OaCsD95unwnvb+QJQkIoXEsgBYri6e5XA5k6oIJXlYWTMHVwWVOP5aGQQVcHBTkDriv/44/xmQ=
    app: cc-node-ts