steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'eu.gcr.io/cicdtest-273912/nodejs', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push','eu.gcr.io/cicdtest-273912/nodejs']
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]
images: ['eu.gcr.io/cicdtest-273912/nodejs']
